### PR TITLE
Fix the icon search on summary.

### LINKED ISSUE #2: Static icon in Summary
## Summary
The summary page shows always the sunny icon. 

## Expected behaviour
The icon in summary should change simultaneously with the daily weather.

### PR DESCRIPTION
**Pull request by zsofiaflorek**
Closes #2

### CODE REVIEW

File: src/Summary.js [hunk 1]
```diff
@@ -25,3 +36,20 @@ export const Summary = ({
...
+    "Light Cloud": lightCloudIcon,
+    "Heavy Rain": heavyRainIcon,
+    Hail: hailIcon,
+    Clear: clearIcon,
+    HeavyCloud: heavyCloudIcon,
+};
+
+function getIconForWeatherLabel(weatherLabel) {
+    return iconForLabel[weatherLabel] ?? heavyCloudIcon;
+}
```
Comment (marcelltoth) [inline src/Summary.js]: This is duplicated in some other file. Can you extract it rather?

**Review by marcelltoth — CHANGES_REQUESTED** [review]

File: src/Summary.css [hunk 2]
```diff
@@ -10,7 +10,7 @@
     color: #88869D;
     padding-top: 80px;
     padding-bottom: 80px;
-    background-image: url("Cloud-background_grey.png");
+    background-image: url("utils/icons/Cloud-background_blue.png");
```
Comment (marcelltoth) [inline src/Summary.css]: This isn't an icon, right?

File: src/DailyWeatherCard.js [hunk 3]
```diff
@@ -1,15 +1,6 @@
...
-import hailIcon from "./Hail.png";
-import heavyCloudIcon from "./HeavyCloud.png";
-import clearIcon from "./Clear.png";
-import heavyRainIcon from "./HeavyRain.png";
-import lightCloudIcon from "./LightCloud.png";
-import lightRainIcon from "./LightRain.png";
-import showerIcon from "./Shower.png";
-import sleetIcon from "./Sleet.png";
-import snowIcon from "./Snow.png";
-import thunderstormIcon from "./Thunderstorm.png";
```
Comment (marcelltoth) [inline src/DailyWeatherCard.js:11]: Much cleaner 🤩

**Review by marcelltoth — APPROVED** [review]
That one little thing, otherwise it's perfect. Tentative approval.
